version: '3.8'

services:
  master:
    container_name: "master"
    image: "citusdata/citus:latest"
    ports:
      - "5432:5432"
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - citus-net
    command: >
      -c shared_preload_libraries='citus,pg_stat_statements'
      -c pg_stat_statements.track=all
      -c track_activity_query_size=2048
      -c max_connections=1000
      -c shared_buffers=256MB

  manager:
    container_name: "citus_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on:
      - master
    environment: *AUTH
    networks:
      - citus-net

  worker1:
    container_name: "worker1"
    image: "citusdata/citus:latest"
    labels: ["com.citusdata.role=Worker"]
    depends_on:
      - manager
    environment: *AUTH
    volumes:
      - healthcheck-volume:/healthcheck
    networks:
      - citus-net
    command: >
      bash -c "
      /wait-for-manager.sh &&
      /docker-entrypoint.sh postgres
      -c shared_preload_libraries='pg_stat_statements'
      -c pg_stat_statements.track=all
      -c track_activity_query_size=2048
      -c max_connections=1000
      -c shared_buffers=256MB
      "

  worker2:
    container_name: "worker2"
    image: "citusdata/citus:latest"
    labels: ["com.citusdata.role=Worker"]
    depends_on:
      - manager
    environment: *AUTH
    volumes:
      - healthcheck-volume:/healthcheck
    networks:
      - citus-net
    command: >
      bash -c "
      /wait-for-manager.sh &&
      /docker-entrypoint.sh postgres
      -c shared_preload_libraries='pg_stat_statements'
      -c pg_stat_statements.track=all
      -c track_activity_query_size=2048
      -c max_connections=1000
      -c shared_buffers=256MB
      "

  worker3:
    container_name: "worker3"
    image: "citusdata/citus:latest"
    labels: ["com.citusdata.role=Worker"]
    depends_on:
      - manager
    environment: *AUTH
    volumes:
      - healthcheck-volume:/healthcheck
    networks:
      - citus-net
    command: >
      bash -c "
      /wait-for-manager.sh &&
      /docker-entrypoint.sh postgres
      -c shared_preload_libraries='pg_stat_statements'
      -c pg_stat_statements.track=all
      -c track_activity_query_size=2048
      -c max_connections=1000
      -c shared_buffers=256MB
      "

  worker4:
    container_name: "worker4"
    image: "citusdata/citus:latest"
    labels: ["com.citusdata.role=Worker"]
    depends_on:
      - manager
    environment: *AUTH
    volumes:
      - healthcheck-volume:/healthcheck
    networks:
      - citus-net
    command: >
      bash -c "
      /wait-for-manager.sh &&
      /docker-entrypoint.sh postgres
      -c shared_preload_libraries='pg_stat_statements'
      -c pg_stat_statements.track=all
      -c track_activity_query_size=2048
      -c max_connections=1000
      -c shared_buffers=256MB
      "

  worker5:
    container_name: "worker5"
    image: "citusdata/citus:latest"
    labels: ["com.citusdata.role=Worker"]
    depends_on:
      - manager
    environment: *AUTH
    volumes:
      - healthcheck-volume:/healthcheck
    networks:
      - citus-net
    command: >
      bash -c "
      /wait-for-manager.sh &&
      /docker-entrypoint.sh postgres
      -c shared_preload_libraries='pg_stat_statements'
      -c pg_stat_statements.track=all
      -c track_activity_query_size=2048
      -c max_connections=1000
      -c shared_buffers=256MB
      "

  worker6:
    container_name: "worker6"
    image: "citusdata/citus:latest"
    labels: ["com.citusdata.role=Worker"]
    depends_on:
      - manager
    environment: *AUTH
    volumes:
      - healthcheck-volume:/healthcheck
    networks:
      - citus-net
    command: >
      bash -c "
      /wait-for-manager.sh &&
      /docker-entrypoint.sh postgres
      -c shared_preload_libraries='pg_stat_statements'
      -c pg_stat_statements.track=all
      -c track_activity_query_size=2048
      -c max_connections=1000
      -c shared_buffers=256MB
      "

  worker7:
    container_name: "worker7"
    image: "citusdata/citus:latest"
    labels: ["com.citusdata.role=Worker"]
    depends_on:
      - manager
    environment: *AUTH
    volumes:
      - healthcheck-volume:/healthcheck
    networks:
      - citus-net
    command: >
      bash -c "
      /wait-for-manager.sh &&
      /docker-entrypoint.sh postgres
      -c shared_preload_libraries='pg_stat_statements'
      -c pg_stat_statements.track=all
      -c track_activity_query_size=2048
      -c max_connections=1000
      -c shared_buffers=256MB
      "

networks:
  citus-net:
    driver: bridge

volumes:
  healthcheck-volume:
